# Generated by Django 4.2.10 on 2024-05-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclassroom',
            name='date_assigned',
        ),
    ]
